### ISSUE TITLE
Daily Claim Platinum addon conflicts

### ISSUE THREAD

**Issue by ExiledDitto** [Emmotes/IC_Addons#1]
BrivGemFarm LevelUp - DCP prevents the "Briv MinLevel before stacking (offline)" option from engaging. The script gets to the stack zone and immediately restarts the game without changing Briv's level. Worth noting that I can set his main min/max level higher and the addon handles that fine.

Potion Sustain - DCP prevents the addon from changing the automated potions in the modron core during offline stacking. It always shows "Pending potion swapping. Waiting for next offline stack." but never does it.

I don't think either of these are load conflicts. I've tried many configurations and even turning the DCP options off, but as long as the addon is loaded the other two don't function as I need them to.

**Comment by Emmotes** [comment]
Which version of CDP have you been using?

**Comment by Emmotes** [comment]
This should be fixed in v0.0.3+. Reissue if it's still broken for you.
